name: Deploy to Vercel

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Node.js
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              # - name: Pull Vercel Environment Information
              #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
              # - name: Build Project Artifacts
              #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
              # - name: Deploy to Vercel
              #   env:
              #       VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
