name: Deploy to Vercel

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to Vercel
              uses: vercel/actions/login@v2
              with:
                  token: ${{ secrets.VERCEL_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                  push: true
                  tags: nest-api:latest
                  file: ./Dockerfile
            - name: Deploy to Vercel
              uses: vercel/actions/deploy@v12
              with:
                  token: ${{ secrets.VERCEL_TOKEN }}
                  orgId: your-vercel-org-id
                  projectId: your-vercel-project-id
                  dockerImage: nest-api:latest
                  buildCommand: |
                  outputDirectory: .
